packages:
  - packages/*
  - docs
  - packages/*/playground

catalog:
  '@antfu/eslint-config': ^4.17.0
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/markdown-it': ^3.8.1
  '@shikijs/transformers': ^3.8.1
  '@shikijs/twoslash': ^3.8.1
  '@shikijs/vitepress-twoslash': ^3.8.1
  '@types/eslint': ^9.6.1
  '@types/node': ^24.0.15
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@typescript/ata': ^0.9.8
  '@typescript/twoslash': ^3.2.9
  '@typescript/vfs': ^1.6.1
  '@unocss/reset': ^66.3.3
  '@vitest/coverage-v8': ^3.2.4
  '@vue/language-core': ^3.0.3
  '@vueuse/core': ^13.5.0
  bumpp: ^10.2.0
  eslint: ^9.31.0
  esno: ^4.8.0
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  idb-keyval: ^6.2.2
  jiti: ^2.4.2
  lint-staged: ^16.1.2
  lz-string: ^1.5.0
  mlly: ^1.7.4
  ohash: ^2.0.11
  preact: ^10.26.9
  pretty-format: ^30.0.5
  react: ^19.1.0
  sass: ^1.89.2
  shiki: ^3.8.1
  simple-git-hooks: ^2.13.0
  tslib: ^2.8.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.3.3
  unplugin-vue-components: ^28.8.0
  unstorage: ^1.16.1
  vite: ^7.0.5
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.8
  vitest: ^3.2.4
  vue: ^3.5.17

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
